---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: api-service-account
 namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
  namespace: test
rules:
- apiGroups: [ "", "rbac.authorization.k8s.io" ]
  resources: [ "deployments", "pods", "services", "namespaces"]
  verbs: [ "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-pod-reader
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: api-service-account
  namespace: test